FROM 0x77dev/containers:python3-node14

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y build-essential \
    cmake libopenblas-dev \
    libdlib-dev python3-opencv \
    libopencv-dev
